#!/bin/bash

FILES_DIR="./files"

for file in "${FILES_DIR}"/*.txt; do
  filename=$(basename "$file")

  # 첫 번째 알파벳 추출
  first_letter=$(echo $filename | cut -c1 | tr '[:upper:]' '[:lower:]')

  dest_dir="${first_letter}"

  if [ -d "$dest_dir" ]; then
    mv "$file" "$dest_dir/"
    echo "Moved ${filename} to ${dest_dir}/"
  fi
done
